# Generated by Django 5.0.6 on 2024-06-02 10:34

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):
    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="Portfolio",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("name", models.CharField(max_length=255)),
                ("expiry", models.CharField(default="weekly_exp", max_length=50)),
                ("premium_gap", models.FloatField(blank=True, null=True)),
                ("start", models.TimeField()),
                ("end", models.TimeField()),
                ("target", models.FloatField()),
                ("stop_loss", models.FloatField()),
            ],
        ),
        migrations.CreateModel(
            name="LegSettings",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("state", models.IntegerField()),
                ("right", models.CharField(max_length=1)),
                ("txn", models.CharField(max_length=10)),
                ("execution_time", models.TimeField(blank=True, null=True)),
                ("sqoff_time", models.TimeField(blank=True, null=True)),
                ("count_sl", models.IntegerField()),
                ("count_tp", models.IntegerField()),
                ("wait_n_trade", models.IntegerField(blank=True, null=True)),
                ("target_premium", models.FloatField()),
                ("stop_loss", models.FloatField(blank=True, null=True)),
                ("take_profit", models.FloatField(blank=True, null=True)),
                ("ProfitLockThreshold", models.FloatField(blank=True, null=True)),
                ("LockProfitAt", models.FloatField(blank=True, null=True)),
                ("IncreaseInProfitForTrail", models.FloatField(blank=True, null=True)),
                ("TrailProfitBy", models.FloatField(blank=True, null=True)),
                ("SL_TrailTrigger", models.FloatField(blank=True, null=True)),
                ("SL_Trail_Amt", models.FloatField(blank=True, null=True)),
                (
                    "portfolio",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="leg_settings",
                        to="portfolio.portfolio",
                    ),
                ),
            ],
        ),
    ]
